server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: rooot
    url: jdbc:mysql://localhost:3306/AR_Module
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
reg-app:
  messages:
    fail : User Register  Fail...!
    success : User Register  Successfully...!
    #SSNWebUrl : https://ssa-web-api-herokuapp.com/state/{ssn}
    SSNWebUrl : http://localhost:9393/state/{ssn}